#!/bin/bash

CONFIGDIR="$HOME/.noipupdater"
CONFIGFILE="$CONFIGDIR/noipupdater.conf"
LOGFILE="$CONFIGDIR/log/noipupdater.log"
STOREDIPFILE="$CONFIGDIR/cache/current_ip"
USERAGENT="Simple Bash No-IP Updater/0.4 antoniocs@gmail.com"

[ -d $CONFIGDIR ] || mkdir $CONFIGDIR
[ -d $CONFIGDIR/log ] || mkdir $CONFIGDIR/log
[ -d $CONFIGDIR/cache ] || mkdir $CONFIGDIR/cache
[ -e $STOREDIPFILE ] || touch $STOREDIPFILE

set -e

if [ -f $CONFIGFILE ]; then
    source $CONFIGFILE
else
    echo "Please create $CONFIGFILE and fill in the variables:
    USERNAME, PASSWORD, HOST, SSID
    optional: ROUTERURL, ROUTERUSER, ROUTERPASSWORD, ROUTERWANIPSTR"
    exit 1
fi

if [ -n $SSID ]; then
    CURRENTSSID=$(/usr/sbin/iw wlp3s0 link | grep SSID | cut -d' ' -f2)
    [ $CURRENTSSID != $SSID ] && exit 1
fi

if [ -n $ROUTERURL ]; then
    NEWIP=$(curl -s "http://$ROUTERUSER:$ROUTERPASSWORD@$ROUTERURL" | grep -m 1 $ROUTERWANIPSTR | cut -d"'" -f2)
else
    NEWIP=$(wget -O - http://icanhazip.com/ -o /dev/null)
fi

STOREDIP=$(cat $STOREDIPFILE)

if [ "$NEWIP" != "$STOREDIP" ]; then
    RESULT=$(curl -k -s --user-agent "$USERAGENT" "https://$USERNAME:$PASSWORD@dynupdate.no-ip.com/nic/update?hostname=$HOST&myip=$NEWIP")
    echo $NEWIP > $STOREDIPFILE
    echo "[$(date +"%Y-%m-%d %H:%M:%S")] $RESULT" >> $LOGFILE
fi
