#!/bin/bash

CONFIGDIR="$HOME/.noipupdater"
CONFIGFILE="$CONFIGDIR/noipupdater.conf"
LOGFILE="$CONFIGDIR/log/noipupdater.log"
STOREDIPFILE="$CONFIGDIR/cache/current_ip"
USERAGENT="Simple Bash No-IP Updater/0.4 antoniocs@gmail.com"

[ -d $CONFIGDIR ] || mkdir $CONFIGDIR
[ -d $CONFIGDIR/log ] || mkdir $CONFIGDIR/log
[ -d $CONFIGDIR/cache ] || mkdir $CONFIGDIR/cache
[ -e $STOREDIPFILE ] || touch $STOREDIPFILE

if [ -f $CONFIGFILE ]; then
    . $CONFIGFILE
else
    echo "Please create $CONFIGFILE and fill in the variables: USERNAME, PASSWORD, HOST"
    exit 1
fi

NEWIP=$(wget -O - http://icanhazip.com/ -o /dev/null)
STOREDIP=$(cat $STOREDIPFILE)

if [ "$NEWIP" != "$STOREDIP" ]; then
	RESULT=$(wget -O - -q --user-agent="$USERAGENT" --no-check-certificate "https://$USERNAME:$PASSWORD@dynupdate.no-ip.com/nic/update?hostname=$HOST&myip=$NEWIP")

	LOGLINE="[$(date +"%Y-%m-%d %H:%M:%S")] $RESULT"
	echo $NEWIP > $STOREDIPFILE
else
	LOGLINE="[$(date +"%Y-%m-%d %H:%M:%S")] No IP change"
fi

echo $LOGLINE >> $LOGFILE
